# Generated by Django 3.0.7 on 2020-06-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headline',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='headline',
            name='url',
            field=models.TextField(null=True),
        ),
    ]
